org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.1
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=newnew_attributes
mod_name=NewNew Attributes
mod_license=MIT
mod_version=1.0.7
mod_group_id=com.gam0zing
mod_authors=gam0zing
mod_description=Make attribute great again!